name: Check pull request

on:
  pull_request:
    branches: [main, staging]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.0.1]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 19.0.1
        uses: actions/setup-node@v3
        with:
          node-version: 19.0.1
          cache: 'yarn'
      - run: yarn install
      - run: yarn lint
      #- run: yarn test
